branches:
  only:
  - master
language: python
python:
- 2.7
script:
- make github
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    secure: "fVb9pwVQVqy+1tV/8jF1RCk5Qi644Jwc0r8awAOmCo9yo6xSZUUv5OeGMWnftL6hq2YQlhqC6zJ7TDSW8AXqq5wFsECrQ5QlQwJEqNEnnGsCgLASJVOVHbqA9zO3ZMGSSU+MDA5+FzsykTjS1/QpZGVXCdYRrD26humzeyaS7hw="
